#!/bin/sh

PKB=/home/gremy/gremy.pkb
MEDIAS=/home/gremy/.opencal/materials
GIT_DIR=/home/gremy/git_opc/
OPC=/home/gremy/bin/opencal/opencal

${OPC}

echo "Update git repository..."
rsync ${PKB} ${GIT_DIR}
rsync -r ${MEDIAS} ${GIT_DIR}

cd ${GIT_DIR}

git add .
git commit -m "Auto commit"
