#!/bin/sh

# OpenCAL v3
# Copyright (c) 2011 Jérémie DECOCK

PKB_FILE=$1
PKB_DTD=/home/gremy/.opencal/pkb.dtd
PKB_SCHEMA=/home/gremy/.opencal/pkb.xsd

if [ -f "${PKB_FILE}" ]
then
    echo "checking ${PKB_FILE}..."
else
    echo "usage: $0 PKB_FILE"
fi

# SYNTAX
echo -n "* well-formed : "
xmllint --noout "${PKB_FILE}"

if [ $? -eq 0 ]
then
    echo "ok"
else
    echo "fails"
    exit $?
fi

# DTD
echo -n "* dtd-valid : "
xmllint --noout --dtdvalid "${PKB_DTD}" "${PKB_FILE}"

if [ $? -eq 0 ]
then
    echo "ok"
else
    echo "fails"
fi

# SCHEMA
echo -n "* schema-valid : "
xmllint --noout --schema "${PKB_SCHEMA}" "${PKB_FILE}"

