#!/bin/sh

# OpenCAL v3
# Copyright (c) 2006,2007,2008,2009,2010,2011 Jérémie DECOCK <jd.jdhp@gmail.com>

LIB_DIR="/usr/share/java"

JCOMMON_LIB="jcommon.jar"
JFREECHART_LIB="jfreechart.jar"
JUNIT_LIB="junit4.jar"
SWT_LIB="swt.jar"

OPENCAL_ROOT=$(dirname "$0")

BIN="${OPENCAL_ROOT}/bin"
LIBS="${CLASS_DIR}:${LIB_DIR}/${JCOMMON_LIB}:${LIB_DIR}/${JFREECHART_LIB}:${LIB_DIR}/${JUNIT_LIB}:${LIB_DIR}/${SWT_LIB}"

#OPTS="-Dopencal.userproperties.location=devel.properties"
OPTS=

if [ -e ~/opencal.lock ]
then
    zenity --error --title="Error" --text="OPC already run (~/opencal.lock)"
else
    touch ~/opencal.lock

    #java ${OPTS} $@ -cp ${LIBS} -jar ${OPENCAL_ROOT}/opencal.jar
    #java ${OPTS} $@ -cp ${BIN}:${LIBS} org.jdhp.opencal.OpenCAL
    java ${OPTS} $@ -cp ${BIN}:${LIBS} org.jdhp.opencal.ui.swt.MainWindow

    rm ~/opencal.lock
fi
