#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright (c) 2012 Jérémie DECOCK (http://www.jdhp.org)

import argparse
import xml.sax

from xml.sax.handler import ContentHandler, ErrorHandler

# ContentHandler ############################

class MyContentHandler(ContentHandler):
    """Get known words in english questions"""

    def __init__(self):
        self.is_tag_element = False
        self.tag_value = ""

    def startDocument(self):
        self.tags = {}

    def endDocument(self):
        print(len(self.tags))
        print(self.tags)
        print() 

    def startElement(self, name, attr):
        if name == "tag":
            self.is_tag_element = True
            self.tag_value = ""

    def endElement(self, name):
        if name == "tag":
            if self.tag_value in self.tags:
                self.tags[self.tag_value] += 1
            else:
                self.tags[self.tag_value] = 1
            self.is_tag_element = False

    def characters(self, ch):
        if self.is_tag_element:
            self.tag_value += ch

# ErrorHandler ##############################

class MyErrorHandler(ErrorHandler):
    def fatalError(self, exception):
        print("Fatal error:", exception)

    def error(self, exception):
        print("Error:", exception)

    def warning(self, exception):
        print("Warning:", exception)


def main():
    """Main function"""

    # Parse program arguments
    argparser = argparse.ArgumentParser(description='OPC tool.')
    argparser.add_argument('filenames', nargs='+', metavar='FILE', help='file to read')
    args = argparser.parse_args()

    # Make XML parser
    xmlreader = xml.sax.make_parser()
    xmlreader.setContentHandler(MyContentHandler())
    xmlreader.setErrorHandler(MyErrorHandler())

    # Parse XML files
    for filename in args.filenames:
        print(filename, end=' ')
        xmlreader.parse(filename)

if __name__ == '__main__':
    main()
